#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]

//! Low-level FFI bindings to iOS frameworks and APIs
//!
//! This crate provides raw bindings to iOS system frameworks including:
//! - Objective-C runtime
//! - Mach kernel APIs
//! - Foundation framework types
//! - UIKit framework (when enabled)
//!
//! # Bindings Generation
//!
//! All bindings are **automatically generated** from the iOS SDK headers using bindgen.
//! The SDK must be present in `submodules/sdks/` (Theos SDK format).
//!
//! # Features
//!
//! - `runtime`: Link against actual iOS frameworks (requires iOS/macOS or cargo-zigbuild)
//! - `foundation`: Foundation framework bindings
//! - `uikit`: UIKit framework bindings
//! - `mach`: Mach kernel API bindings (enabled by default)
//!
//! # Build Modes
//!
//! By default, this crate builds in header-only mode, allowing development
//! on any platform. Enable the `runtime` feature to link against actual
//! iOS frameworks.

// Include bindings generated by build.rs from SDK headers
pub mod objc {
    //! Objective-C runtime bindings (auto-generated from objc/runtime.h)
    #![allow(clippy::all)]
    #![allow(warnings)]
    include!(concat!(env!("OUT_DIR"), "/objc.rs"));
}

pub mod mach {
    //! Mach kernel API bindings (auto-generated from mach/*.h)
    #![allow(clippy::all)]
    #![allow(warnings)]
    include!(concat!(env!("OUT_DIR"), "/mach.rs"));
}

pub mod foundation {
    //! Foundation framework type bindings (auto-generated)
    #![allow(clippy::all)]
    #![allow(warnings)]
    include!(concat!(env!("OUT_DIR"), "/foundation.rs"));
}

// Re-export commonly used types for convenience
pub use objc::{Class, Ivar, Method, SEL};
